name: journalapp

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    command: redis-server --appendonly yes --appendfsync everysec


  postgres:
    image: postgres:16
    restart: unless-stopped
      
    ports:
      - "5432:5432"
      
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
        
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  redis-data:

  postgres-data:
    external: true
